version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATA_PROVIDER=socrata
      - CORS_ALLOW_ORIGINS=http://localhost:8501
    volumes:
      - ./data:/app/data
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true

volumes:
  data:
